import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/banner";
import Navbar from "../components/navbar/navbar";
import Card from "../components/card/card";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="ben@ben.com" />
      <Banner
        title="Guardians Of The Galaxy"
        subTitle="Awesome Movie"
        imgUrl="/static/guardians.jpg"
      />
      <Card imgUrl="/static/guardians.jpg" size="large" />
      <Card imgUrl="/static/guardians.jpg" size="medium" />
      <Card imgUrl="/static/guardians.jpg" size="small" />
    </div>
  );
}
